/**
* Automatically Generated by Palmares at 2022-06-10T16:47:59.931Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    databaseName: "macapa",
    dependency: "",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"MacapaContacts",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":200}),
					celular:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"celular","customAttributes":{},"attributeName":"celular","maxLength":20}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "macapa_contacts",
					managed: true,
					ordering: [],
					indexes: [],
					databases: ["macapa"],
					customOptions: {},
				}
    		),
        ]
    }
}